### ISSUE TITLE
Doesn't work with Windows and Photoshop 2022/2023

### ISSUE THREAD

**Issue by evolucja** [joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script#30] opened 2023-11-25 17:46 UTC
Hi, it looks like a ton of a great work and I'd love to use it. 

However I downloaded the standalone example, cleared the output folded and executed the script in Photoshop. It just opened the "example-mockup.psd" and did nothing more. No errors, messages, no output.

Any idea if it was tested under Windows and Photoshop 2022/2023?

What can I check?

Best regards
Dave

@EDIT
Looks to be the same on CC 2019..

**Comment by evolucja** [comment] 2023-11-25 19:03
After some debugging I made it working but not sure how it should be properly fixed.

I changed relative paths to:
![image](https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script/assets/990929/6bdd6e98-e2f1-4588-a3bd-1270a4c9ee5e)

And commented out:
```
  // Input folder path
  // if ( data.doc.input && typeof data.doc.input === 'string' ) data.doc.input = [ data.doc.input ];
  // each( data.doc.input, function( item, index ) {
  //   data.doc.input[ index ] = absolutelyRelativePath( data.doc.input[index] ).decoded;
  // });
```
because the script was failing at this moment (something undefined).

So I'm pretty sure it's something about Windows paths..

**Comment by joonaspaakko** [comment] 2023-11-30 21:14
@evolucja, I didn't have time to even attempt a fix, but I took a look at it and sure enough it failed to run Windows. That said I tested it on PS CS6, just because I didn't have immediate access to CC. I have a feeling it could be the same issue even though I got an error dialog. 

I found out that the previous version of the script 1.8 worked just fine. I was wondering if you could try [Standalone example - Version 1.8](https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement.js-Photoshop-script-standalone-example/archive/273ff7ef0fa5fd7c32e7e3d5e0639698903b6204.zip) (direct download link).

**Comment by panagakis** [comment] 2023-12-25 07:30
@joonaspaakko i really appreciate your work. I can confirm that 1.8 does indeed work but not the other one. Are there any downsides to use the 1.8 version compared to the latest? Thank you

**Comment by panagakis** [comment] 2023-12-25 07:45
@joonaspaakko I tried but 1.8 stopped right after 3-4 saves of my files. I used @evolucja method which works perfectly and i also added the webp file in the input formats and everything worked perfectly fine with the same images i tried in 1.8.

**Comment by joonaspaakko** [comment] 2023-12-25 10:53
> 1.8 stopped right after 3-4 saves of my files. — I also added the webp file in the input formats

If it saves any files, I would think it's not about the inability to figure out the path, which should be done the same way for each file. Are you sure it didn't just ignore your webp files on the first run before you added it to the input formats?

**Comment by nfourteen** [comment] 2024-02-02 16:28
@joonaspaakko Th issue here I found was the error `undefined is not an object` being thrown when the settings config didn't contain an `input` property at the `doc` level (to override the `smartObjects[].input` property). The `undefined` value is assigned here: https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script/blob/master/script/Batch%20Mockup%20Smart%20Object%20Replacement.jsx#L450

I fixed it by adding `|| []` to the loop at L456 to:
```js
  each( data.doc.input || [], function( item, index ) {
    data.doc.input[ index ] = absolutelyRelativePath( data.doc.input[index] ).decoded;
  });
```

That fixes the error. But now it's not processing correctly. I think this has something to do with my settings config and data structure. The first `for` loop conditional is `true` here: https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script/blob/master/script/Batch%20Mockup%20Smart%20Object%20Replacement.jsx#L226, so the loop is never entered and smart objects are never swapped. Not sure what's going on here, but working on that now.

**Comment by joonaspaakko** [comment] 2024-02-02 16:41
@nfourteen, all I can say for now (on mobile) is that if `data.doc.input` doesn't return anything, the issue is somewhere deeper. It should always find a mockup unless the settings script is somehow pointing into the wrong place. I would use any of the examples to debug this because they use relative paths that are known to work. Hint: The issue should be somewhere in the diff between v.1.8 and v.1.9.

**Comment by nfourteen** [comment] 2024-02-02 17:19
@joonaspaakko Yup, I just figured out the `input` property at the smart object level was pointing to a file and not a folder. I also believe that the `input` property can't point to the directory the settings config file is in (that also didn't work)? But with some adjustments (moving the `input` file down a directory and pointing `input` to said directory), the v1.9 is up and running for me.

I did have to leave the fix in place. The `data.doc.input` remained `undefined` at the `mockup` level as the settings file didn't define it. To reproduce:

```
mockups([
  {
    input: '',   // leave this property out of settings config
    smartObjects: [
      {
        target: '@so',
        input: './image',
        inputNested: false,
      },
    ]
  },
]);
```

Then when `replaceLoopOptionsFiller` executes, the script ends up running:

```
...

  if ( rawData.inputNested ) data.doc.inputNested = rawData.inputNested;
  data.doc.input  = rawData.input; // this is undefined currently
  data.doc.inputFormats = rawData.inputFormats;
  data.doc.inputIndex = 0;
  
  // Input folder path
  if ( data.doc.input && typeof data.doc.input === 'string' ) data.doc.input = [ data.doc.input ];
  each( data.doc.input, function( item, index ) { // each tries to iterate over "undefined"
    data.doc.input[ index ] = absolutelyRelativePath( data.doc.input[index] ).decoded;
  });

...
```

**Comment by joonaspaakko** [comment] 2024-02-02 17:40
I feel a bit bad that I'm giving you these half passed tips, but the mockup path is defined by [a slightly inconsistent `mockupPath`](https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement.js-Photoshop-script-standalone-example/blob/main/Batch%20replace%20example%20(Run%20this%20file%20in%20PS).jsx#L15) rather than `input`, so it shouldn't work at all unless you changed its "name".

**Comment by nfourteen** [comment] 2024-02-02 18:24
Well, that's my fault. I should've left a little more config in the example...went for too much brevity. The `mockupPath` should be defined within the script to reproduce. I've underlined the property that's causing issues from a screen shot of the docs and attached it here.

<img width="752" alt="Screenshot 2024-02-02 at 1 19 36 PM" src="https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script/assets/14304240/f3f6f433-d93a-407d-8d65-37a6dcad2507">

**Comment by joonaspaakko** [comment] 2024-02-02 23:24
Gotcha. If you make a pull request I can take a look at it. 

> I still haven't quite read everything thoroughly so I'm not a 100% if you posted all of the code you changed. If you did, it wasn't a big change, I can easily test that too.

**Comment by schroef** [comment] 2024-02-22 00:04
Seems like the script stop because it's missing props or attributes in the Jax file which has the paths. Seem the if data.doc.inoit should be wrapped in a try/catch

I've tried debugging where it stops and it's at the part where it's checking for input ik data.doc.input

**Comment by joonaspaakko** [comment] 2024-02-22 23:09
@schroef, I guess I'll see if I have time to fix it this over the weekend. I was kinda waiting for @nfourteen to make a pull request not to steal his thunder, but I'll either fix it this weekend or rollback 1.8 if I don't have enough time.

**Comment by schroef** [comment] 2024-02-22 23:51
Well I looked at his profile and he either uses something else or only works offline. There is nothing there.

Did this version have more features?

**Comment by nfourteen** [comment] 2024-02-23 03:50
@joonaspaakko @schroef I apologize...I got sidetracked on some other features for the script and work. I'll get a few PRs up for some things I've been working on tomorrow or Sat, including the fix for this issue.

**Comment by joonaspaakko** [comment] 2024-02-23 16:21
> Did this version have more features?

@schroef pretty much 2 niche features that most users probably don't need.

https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script/blob/fc546baacf6ea29cab95eb3b97cb869ae2baeccd/script/Batch%20Mockup%20Smart%20Object%20Replacement.jsx#L39-L51

**Closed** 2024-02-25 19:49 UTC
